In [1]:
import numpy as np
import math

In [2]:
def legal_move(position, board):
    "Returns if a move is legal"
    return np.all((position >= 0) & (position <= 4)) and board[tuple(position)] == ""

In [3]:
def get_legal_moves(piece, board):
    """
    Return posible next positions based on the type of piece, its position on the board, and the board itself
    ---
    Returns a numpy array of posible moves
    """

    pos = position(piece, board)

    if (pos[0] + pos[1]) % 2 == 0:
        movement_set = np.array(
            [
                (-1,-1), (0,-1), (1,-1),
                (-1, 0),         (1, 0), 
                (-1, 1), (0, 1), (1, 1)
            ]
        )
    else:
        movement_set = np.array(
            [
                        (0,-1),
                (-1, 0),         (1, 0), 
                        (0, 1),
            ]
        )

    get_legal_moves = np.array([m+pos for m in movement_set if legal_move(m+pos, board)])

    if piece[0] == "0":

        jump_movement = np.array([m*2 + pos for m in movement_set if legal_move(m*2 + pos, board) and board[tuple(m + pos)] == "X"])

        if piece[1] == 0:

            c_array = np.array([a for a in [get_legal_moves, jump_movement] if a.size != 0])
            if c_array.size != 0:
                get_legal_moves = np.concatenate(c_array)

        else:

            get_legal_moves = jump_movement


    return pos, get_legal_moves

def result(piece, board):

    """ Returns who wins (if any)"""

    if piece[0] == "0" and get_legal_moves(piece, board)[1].size == 0: #If the hare can't move
        res = "Hare loses"
    elif np.count_nonzero(board == "X") <= 9:
        res = "Hare wins"
    else:
        res = "Not yet"

    return res

def position(piece, board):
    "Returns the position of a piece on the board as a tuple"

    if piece[0] == "0":
        pos = tuple(np.argwhere(board == "0")[0])
    else:
        pos = tuple(np.argwhere(board == "X")[piece[1]])

    return pos


In [4]:
def is_win(piece, board):

    """ Returns who wins (if any)"""

    if piece[0] == "0":
        if np.count_nonzero(board == "X") <= 9:
            return True
        else:
            return False
    else:
        if get_legal_moves((True,0), board)[1].size == 0:
            return True
        else:
            return False

In [5]:
board = np.array([
    ['' , '' , '' , '' , 'X'],
    ['X', 'X', 'X', 'X', '' ],
    ['' , 'X', 'X', '' , 'X'],
    ['' , '' , '' , 'X', 'X' ],
    ['' , '' , '' , 'X', '0']
    ])
piece = ("X", 0) 

# "X" if hunters, "0" if hare
# The second number indicates the number of consecutive moves by a hare or the index of the hunter, 


pos, movements = get_legal_moves(piece, board)

print(f"Is win? -> {is_win(piece, board)}")
print(f"Piece in position {pos} can move to {movements}")

Is win? -> False
Piece in position (0, 4) can move to [[0 3]
 [1 4]]


In [6]:
def execute_move(board, move, piece):

    """
    Updates the board with a move
    """

    start, end = move

    if piece[0] == "0":
        
        diff = np.array(end)-np.array(start)

        if 2 in np.abs(diff): # Salto

            pos_cazador = np.array(start) + (diff/2).astype(int)


            board[tuple(start)] = ""
            board[tuple(pos_cazador)] = ""
            board[tuple(end)] = "0"

        else:

            board[tuple(start)] = ""
            board[tuple(end)] = "0"

    else:
        board[tuple(start)] = ""
        board[tuple(end)] = "X"

    return board
    
    

In [7]:
board = np.array([
    ['' , '' , '' , '' , 'X'],
    ['X', 'X', 'X', 'X', '' ],
    ['' , 'X', 'X', '' , ''],
    ['' , '' , '' , '', '' ],
    ['' , '' , '' , 'X', '0']
])
piece = ("0", 0) 

# The first number indicates True if hare, False if hunters
# The second number indicates the number of consecutive moves by a hare or the index of the hunter, 


pos, movements = get_legal_moves(piece, board)

print(f"Is win? -> {is_win(piece, board)}")
print(f"Piece in position {pos} can move to {movements}")


move = [[4, 4], [4, 2] ] # [start, end]

execute_move(board, move, piece)

Is win? -> True
Piece in position (4, 4) can move to [[3 3]
 [3 4]
 [4 2]]


/home/fran/.local/lib/python3.7/site-packages/ipykernel_launcher.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


array([['', '', '', '', 'X'],
       ['X', 'X', 'X', 'X', ''],
       ['', 'X', 'X', '', ''],
       ['', '', '', '', ''],
       ['', '', '0', '', '']], dtype='<U1')

In [8]:
[0]*(3-1)+[1]

[0, 0, 1]

In [9]:
3/2

1.5

In [12]:
np.array([""]).tolist()

['']

In [2]:
[abs(-2)]

[2]

In [16]:
toy = np.array([[[[0,1],[0,0]],[[0,0],[0,0]]],[[[0,0],[0,0]],[[0,0],[0,0]]]])
print(toy)

[[[[0 1]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]


In [9]:
ravel = toy.ravel()
ravel

array([0, 1, 1, 0, 0, 2, 2, 0, 0, 3, 3, 0, 0, 4, 4, 0])

In [10]:
np.reshape(ravel, (2,2,2,2))

array([[[[0, 1],
         [1, 0]],

        [[0, 2],
         [2, 0]]],


       [[[0, 3],
         [3, 0]],

        [[0, 4],
         [4, 0]]]])

In [6]:
np.rot90(toy, k = 2)

array([[[[0, 4],
         [4, 0]],

        [[0, 3],
         [3, 0]]],


       [[[0, 2],
         [2, 0]],

        [[0, 1],
         [1, 0]]]])

In [17]:
np.rot90(np.array([[np.rot90(y_0).tolist() for y_0 in x_0] for x_0 in toy]))

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[1, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]])

In [11]:
np.fliplr(np.array([[np.fliplr(y_0).tolist() for y_0 in x_0] for x_0 in toy]))

array([[[[2, 0],
         [0, 2]],

        [[1, 0],
         [0, 1]]],


       [[[4, 0],
         [0, 4]],

        [[3, 0],
         [0, 3]]]])

In [12]:
np.fliplr(np.array([[1,2],[3,4] ]))

array([[2, 1],
       [4, 3]])

In [15]:
np.reshape(np.array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0]), (2,2,2,2))

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]])